import { MarketingLayout } from '../MarketingLayout'

const legalTabs = [
  { label: 'Terms of Service', href: '/terms-condition' },
  { label: 'Privacy Statement', href: '/privacy-statement' },
  { label: 'Privacy Policy', href: '/privacy-policy' },
  { label: 'Cookie Policy', href: '/cookie' },
  { label: 'Refund Policy', href: '/refund-policy' },
]

export default function PrivacyPolicyPage() {
  return (
    <MarketingLayout>
      <section className="pt-24 pb-16">
        <div className="mx-auto max-w-4xl px-6">
          <h1 className="text-3xl font-bold text-slate-900">Privacy Policy</h1>
          <div className="mt-4 flex flex-wrap gap-3">
            {legalTabs.map((tab) => (
              <a key={tab.label} href={tab.href} className="text-sm text-[#0494fc] hover:underline">
                {tab.label}
              </a>
            ))}
          </div>

          <div className="prose prose-slate mt-8 max-w-none text-sm leading-7 text-slate-700">
            <p className="font-semibold">Updated at March 14th, 2024</p>
            <p>
              LightForth ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains
              how your personal information is collected, used, and disclosed by LightForth.
            </p>
            <p>
              This Privacy Policy applies to our app, and its associated subdomains (collectively, our "Service")
              alongside our application, LightForth. By accessing or using our Service, you signify that you have
              read, understood, and agree to our collection, storage, use, and disclosure of your personal information
              as described in this Privacy Policy and our Terms of Service.
            </p>

            <h2 className="text-xl font-bold text-slate-900 mt-8">Definitions and key terms</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser.</li>
              <li><strong>Company:</strong> refers to LightForth LLC, (Dallas, USA).</li>
              <li><strong>Country:</strong> where LightForth is based, in this case is USA.</li>
              <li><strong>Customer:</strong> refers to the company, organization or person that signs up to use the LightForth Service.</li>
              <li><strong>Device:</strong> any internet connected device such as a phone, tablet, computer or any other device.</li>
              <li><strong>IP address:</strong> Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address.</li>
              <li><strong>Personal Data:</strong> any information that directly, indirectly, or in connection with other information allows for the identification or identifiability of a natural person.</li>
              <li><strong>Service:</strong> refers to the service provided by LightForth as described in the relative terms.</li>
            </ul>

            <h2 className="text-xl font-bold text-slate-900 mt-8">What Information Do We Collect?</h2>
            <p>We collect information from you when you visit our app, register on our site, place an order, subscribe to our newsletter, respond to a survey or fill out a form.</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Name / Username</li>
              <li>Phone Numbers</li>
              <li>Email Addresses</li>
              <li>Mailing Addresses</li>
              <li>Job Titles</li>
              <li>Billing Addresses</li>
              <li>Debit/credit card numbers</li>
            </ul>

            <h2 className="text-xl font-bold text-slate-900 mt-8">How Do We Use The Information We Collect?</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>To personalize your experience</li>
              <li>To improve our app</li>
              <li>To improve customer service</li>
              <li>To process transactions</li>
              <li>To administer a contest, promotion, survey or other site feature</li>
              <li>To send periodic emails</li>
            </ul>

            <h2 className="text-xl font-bold text-slate-900 mt-8">How Do We Protect Your Information?</h2>
            <p>
              We implement a variety of security measures to maintain the safety of your personal information when you
              place an order or enter, submit, or access your personal information. We offer the use of a secure server.
              All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then
              encrypted into our Payment gateway providers database only to be accessible by those authorized with
              special access rights to such systems.
            </p>

            <h2 className="text-xl font-bold text-slate-900 mt-8">Cookies</h2>
            <p>
              LightForth uses "Cookies" to identify the areas of our app that you have visited. A Cookie is a small
              piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance
              the performance and functionality of our app but are non-essential to their use.
            </p>

            <h2 className="text-xl font-bold text-slate-900 mt-8">Changes To Our Privacy Policy</h2>
            <p>
              We may change our Service and policies, and we may need to make changes to this Privacy Policy so that
              they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you
              before we make changes to this Privacy Policy and give you an opportunity to review them before they go
              into effect.
            </p>

            <h2 className="text-xl font-bold text-slate-900 mt-8">Contact Us</h2>
            <p>Don't hesitate to contact us if you have any questions.</p>
            <p>Via Email: support@lightforth.org</p>
            <p>Via this Link: https://www.lightforth.org/contact</p>
          </div>
        </div>
      </section>
    </MarketingLayout>
  )
}
